export const GET_ALL_COMMENT_FOR_A_SINGLE_QUESTION_REQUEST =
    'GET_ALL_COMMENT_FOR_A_SINGLE_QUESTION_REQUEST'
export const GET_ALL_COMMENT_FOR_A_SINGLE_QUESTION_SUCCESS =
    'GET_ALL_COMMENT_FOR_A_SINGLE_QUESTION_SUCCESS'
export const GET_ALL_COMMENT_FOR_A_SINGLE_QUESTION_FAILED =
    'GET_ALL_COMMENT_FOR_A_SINGLE_QUESTION_FAILED'

export const LIKE_DISLIKE_COMMENT_REQUEST = 'LIKE_DISLIKE_COMMENT_REQUEST'
export const LIKE_DISLIKE_COMMENT_SUCCESS = 'LIKE_DISLIKE_COMMENT_SUCCESS'
export const LIKE_DISLIKE_COMMENT_FAILED = 'LIKE_DISLIKE_COMMENT_FAILED'

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED'
