export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED'

export const CANCEL_FRIEND_REQUEST = 'CANCEL_FRIEND_REQUEST'
export const CANCEL_FRIEND_SUCCESS = 'CANCEL_FRIEND_SUCCESS'
export const CANCEL_FRIEND_FAILED = 'CANCEL_FRIEND_FAILED'

export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST'
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS'
export const ACCEPT_FRIEND_FAILED = 'ACCEPT_FRIEND_FAILED'

export const REMOVE_FRIEND_REQUEST = 'REMOVE_FRIEND_REQUEST'
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS'
export const REMOVE_FRIEND_FAILED = 'REMOVE_FRIEND_FAILED'