export const GET_ALL_NOTIFICATION_REQUEST = 'GET_ALL_NOTIFICATION_REQUEST'
export const GET_ALL_NOTIFICATION_SUCCESS = 'GET_ALL_NOTIFICATION_SUCCESS'
export const GET_ALL_NOTIFICATION_FAILED = 'GET_ALL_NOTIFICATION_FAILED'

export const GET_LAST_TEN_NOTIFICATION_REQUEST = 'GET_LAST_TEN_NOTIFICATION_REQUEST'
export const GET_LAST_TEN_NOTIFICATION_SUCCESS = 'GET_LAST_TEN_NOTIFICATION_SUCCESS'
export const GET_LAST_TEN_NOTIFICATION_FAILED = 'GET_LAST_TEN_NOTIFICATION_FAILED'