export const GET_ALL_QUESTIONS_REQUEST = 'GET_ALL_QUESTIONS_REQUEST'
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS'
export const GET_ALL_QUESTIONS_FAILED = 'GET_ALL_QUESTIONS_FAILED'

export const GET_SINGLE_QUESTIONS_REQUEST = 'GET_SINGLE_QUESTIONS_REQUEST'
export const GET_SINGLE_QUESTIONS_SUCCESS = 'GET_SINGLE_QUESTIONS_SUCCESS'
export const GET_SINGLE_QUESTIONS_FAILED = 'GET_SINGLE_QUESTIONS_FAILED'

export const LIKE_DISLIKE_QUESTION_REQUEST = 'LIKE_DISLIKE_QUESTION_REQUEST'
export const LIKE_DISLIKE_QUESTION_SUCCESS = 'LIKE_DISLIKE_QUESTION_SUCCESS'
export const LIKE_DISLIKE_QUESTION_FAILED = 'LIKE_DISLIKE_QUESTION_FAILED'

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST'
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS'
export const CREATE_QUESTION_FAILED = 'CREATE_QUESTION_FAILED'

export const GET_TOP_AND_RECENT_REQUEST = 'GET_TOP_AND_RECENT_REQUEST'
export const GET_TOP_AND_RECENT_SUCCESS = 'GET_TOP_AND_RECENT_SUCCESS'
export const GET_TOP_AND_RECENT_FAILED = 'GET_TOP_AND_RECENT_FAILED'
