export const GET_USER_PROFILE_DETAILS_REQUEST = 'GET_USER_PROFILE_DETAILS_REQUEST'
export const GET_USER_PROFILE_DETAILS_SUCCESS = 'GET_USER_PROFILE_DETAILS_SUCCESS'
export const GET_USER_PROFILE_DETAILS_FAILED = 'GET_USER_PROFILE_DETAILS_FAILED'

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAILED = "USER_PROFILE_UPDATE_FAILED";